$( document ).ready(function() {
	function toggleMenus() {
		$("#accueil").toggleClass("hidden");
		$("#dut").toggleClass("hidden");
		$("#licence").toggleClass("hidden");
		$("#infos").toggleClass("hidden");	
	}
	$(".menu-accueil").click(function(){
		$(".wrap1").addClass("pull-right");
		$(".wrap2").addClass("pull-right");
		$(".wrap3").addClass("pull-right");
		$("#accueil").removeClass("hidden");
		$("#dut").addClass("hidden");
		$("#licence").addClass("hidden");
		$("#infos").addClass("hidden");
	});
	$(".menu-dut").click(function(){
		$(".wrap1").removeClass("pull-right");
		$(".wrap2").addClass("pull-right");
		$(".wrap3").addClass("pull-right");
		$("#accueil").addClass("hidden");
		$("#dut").removeClass("hidden");
		$("#licence").addClass("hidden");
		$("#infos").addClass("hidden");
	});

	$(".menu-licence").click(function(){
		$(".wrap1").removeClass("pull-right");
		$(".wrap2").removeClass("pull-right");
		$(".wrap3").addClass("pull-right");
		$("#accueil").addClass("hidden");
		$("#dut").addClass("hidden");
		$("#licence").removeClass("hidden");
		$("#infos").addClass("hidden");
	});
	$(".menu-infos").click(function(){
		$(".wrap1").removeClass("pull-right");
		$(".wrap2").removeClass("pull-right");
		$(".wrap3").removeClass("pull-right");
		$("#accueil").addClass("hidden");
		$("#dut").addClass("hidden");
		$("#licence").addClass("hidden");
		$("#infos").removeClass("hidden");
	});
});
